### PR TITLE
New async method – <() process substitution

### PR DESCRIPTION
**Pull request by psprint**
This PR makes 2 changes:

1. Adds `$0` handling (to get plugin's root directory) that came up in [plugin standard](https://github.com/zdharma/Zsh-100-Commits-Club/blob/master/Zsh-Plugin-Standard.adoc).

2. Adds asynchronicity via `<( )` substitution. It starts a background task leaving the main process with a read or write file descriptor (`>()` for write), which can be plugged into `zle -F` handler-support code, and [everything seems to work fine](https://asciinema.org/a/NJXTzufpdiVCUOcqsBkxce2oc).

I'm doing this PR for Hacktoberfest, I hope you find it useful (this is needed by the Hactoberfest's rules).

### CODE REVIEW

**Comment by psprint** [comment]
Sorry, I've given an old asciinema recording, which was using not-up-to-date code, [the proper one](https://asciinema.org/a/b7YkyflxmYny6ZUfb3SckHXvy).

**Comment by agkozak** [comment]
This is wonderful, @psprint! I had been meaning to implement this myself but hadn't gotten around to it.

I would like to use your code instead of `zsh-async` or the `TRAPUSR1` technique wherever possible. I can see that there are occasional problems that I'll have to address, though.

The main one is that on Solaris 11.3 (ZSH v5.0.7) and Solaris 11.4 (ZSH v5.3.1) -- and even on Windows with MSYS2, although it only happens occasionally -- the Git status will often not be printed at all for a new prompt until a keystroke is registered. I'm not enough of a master of the ZLE to say why it isn't happening. A quick workaround is

    TMOUT=1
    TRAPALRM() { :; }

I'd prefer not to have to use a trap, though, that might be needed by another plugin. Can you think of a fix for this problem?

On ZSH v5.0.2 (on Ubuntu 18.04) I get the error message `_agkozak_subst_async:4: bad option: -w`. I'm not surprised that I'm having trouble with v5.0.2, though -- even `zsh-async` doesn't work with it, so I use `TRAPUSR1` and the non-asynchronous method as fallbacks.

I'll continue to test things, and soon we'll have a much better prompt. I've merged your code to the `subst-async` branch.

**Comment by agkozak** [comment]
@psprint By the way, what is the ZSH bug that `command true` addresses? I can see that you're fixing it by introducing a slight pause, but have you discussed the bug itself anywhere? I'd love to know more.

**Comment by agkozak** [comment]
@psprint I may have just come up with a better workaround. If I change

    exec {AGKOZAK_ASYNC_FD}< <( _agkozak_branch_status )

to

  exec {AGKOZAK_ASYNC_FD}< =( _agkozak_branch_status )

on Solaris, the problem goes away entirely. I know that, with the latter code, a temporary file is created; that might be less desirable, but perhaps I would only uses on systems that have this problem. Let me know if you have any ideas.

**Comment by psprint** [comment]
The workaround is for Ctrl-C stopping working, it was discussed [here](http://www.zsh.org/mla/workers/2018/msg00966.html).

Great news with =() subst. It's good that there is other method.

In general, when I debugged <( ), it was causing occasional problems (mostly segfaults). It seems to me that the code behind this construct is fragile. But when used just right – stable. So I'm using it and not having problems (except for Solaris you've reported, and some [segfault reports](https://github.com/zdharma/fast-syntax-highlighting/issues/30) for when I've enabled async in F-Sy-h by default – I treat this as a rare phenomenon, not sure if it's a good decision).

**Comment by agkozak** [comment]
@psprint I have confirmed that MSYS2 and Cygwin also require `=()` to work properly. I am working on making the prompt use the `subst-async` method by default on all systems possible, and I will continue to look for any other quirky behavior.

**Comment by agkozak** [comment]
@psprint On WSL (Ubuntu on Windows, in this case), the prompt seems to work perfectly with <() substitution at first. If I launch ZSH in a Gnome terminal using an X server (X410 or VcXsrv), however, the shell locks up on occasion and I have to hit Ctrl-C to get another prompt.

**Comment by agkozak** [comment]
@psprint It's beginning to look as if I have a workaround for the weird behavior on MSYS2/Cygwin/Solaris.

Instead of

    exec {AGKOZAK_ASYNC_FD}< <( _agkozak_branch_status )
    command true

I've got

    case $OSTYPE in
        msys|cygwin|solaris*)
            exec {AGKOZAK_ASYNC_FD}< <( _agkozak_branch_status; command true )
            ;;
        *)
            exec {AGKOZAK_ASYNC_FD}< <( _agkozak_branch_status )
            ;;
      esac
      command true

I'm not quite sure why adding yet another pause with `command true` fixes the problem; I'm just following your lead.

I think I'm close to releasing the new version.

**Comment by agkozak** [comment]
`zle -Fw` seems to have been introduced in ZSH v5.0.3. I'll use the other async methods as fallbacks for older versions.

**Comment by psprint** [comment]
Yes, sorry I didn't wrote about this, i knew about -w limited availability. BTW, `-w` is needed when one want's to callback be a `zle` widget, to have `zle` active and be able to alter/read e.g. `BUFFER`. To refresh a prompt after setting `RPROMPT` or similar variable, function-as-callback (not widget-as-...) might be sufficient? I'm not sure. I was updating `POSTDISPLAY` so I've always needed `-w` and an active `zle`.

As for the `=()` performance, I didn't try it yet so i don't know. However, maybe you observe something that I did. When I was writing the pull request, I made a mistake and assigned `psvar[1]` instead of `psvar[3]`. The effect: something was appearing and quickly disappearing in middle main prompt part, on the left/center. The curiosity: it seemed to appear very quick, sometimes just together with first appearance of a new prompt. I was worried: is the call actually async, maybe it's sync in fact? But catching the `psvar[3]` mistake and a few tests confirmed that there's a delay. I've now ran the `psvar[1]` mistaken version and there was a pause after first entering e.g. `git` (the project) repository, but not when entering it for the second time, so I guess it's just in-OS caching.

BTW, I think that the `zsh-async` method uses the worker and callback to obtain a non-freezing pause between showing the prompt and showing the git branch, but still computing the branch in foreground (this can cause a freeze on large repos). I.e. the worker is given an empty job ":":

```zsh
      _agkozak_zsh_async() {
          async_start_worker agkozak_git_status_worker -n
          async_register_callback agkozak_git_status_worker _agkozak_zsh_async_callback
          async_job agkozak_git_status_worker : #< empty-job? I'm not familiar with zsh-async
      }
```

And then not in background, but in foreground, the callback computes the branch:

```zsh
      _agkozak_zsh_async_callback() {
        psvar[3]=$(_agkozak_branch_status) # this runs branch computation in
                                           # foreground, it can induce a freeze
        zle && zle reset-prompt
        async_stop_worker agkozak_git_status_worker -n
      }
```

**Comment by agkozak** [comment]
@psprint Thanks for your helpful thoughts, as always.

It appears that the `-w` option is not necessary for my purposes at all -- which means that I can use the `subst-async` method for every shell version (going back to ZSH v4.3.10, perhaps even further, if I tweak it more) on every system.

And you're right about `zsh-async`. I've made a change that should eliminate the freezing, I think.

All of the changes are on the `develop` branch. I'll keep testing, but I think I'm getting close to a new release.

**Comment by psprint** [comment]
Good to hear that I could help, it's an interesting prompt I might to try it, currently being on `geometry` train

**Pull request merged**
